package edu.millersville.cs.segfault.ui.menu;

import java.awt.Event;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;

import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.KeyStroke;

import edu.millersville.cs.segfault.model.UMLModel;
import edu.millersville.cs.segfault.ui.UMLWindow;

/**************************************************************************
 * UMLFileMenu is the class responsible for instantiating 
 * the File submenu and handling the user selections for the submenu.
 * @author Kimberlyn Broskie
 *************************************************************************/
public class UMLFileMenu extends JMenu 
						implements ActionListener {
	
	//*************************************************************************
	// Static Instance Variables
	//*************************************************************************
	private static final long serialVersionUID = 2052974378829469666L;

	//FILE MENU VARIABLES
	private static final String fileMenuText = "File";
	private static final String newMenuText = "New";
	private static final String openMenuText = "Open";
	private static final String saveMenuText = "Save";
	private static final String saveAsMenuText = "Save as...";
	private static final String exitMenuText = "Exit";
	
	//*************************************************************************
	// Constructors	
	//*************************************************************************
	
	/**************************************************************************
	 * Constructor to build the File submenu, with each submenu option
	 * having a key accelerator.
	 * @param wFrame the frame for the interface
	 * @param umlPanel the panel for the current UML model
	 *************************************************************************/
	public UMLFileMenu (JFrame wFrame) {
		super(fileMenuText);
		
	   // Create the new menu item and add an action listener and accelerator.	   
	   JMenuItem newItem = new JMenuItem(newMenuText);
	   newItem.addActionListener(this);
	   newItem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_N, Event.CTRL_MASK));
	   
	   // Create the open menu item and add an action listener and accelerator.	   
	   JMenuItem openItem = new JMenuItem(openMenuText);
	   openItem.addActionListener(this);
	   openItem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_O, Event.CTRL_MASK));

	   // Create the save menu item and add an action listener and accelerator.	   
	   JMenuItem saveItem = new JMenuItem(saveMenuText);
	   saveItem.addActionListener(this);
	   saveItem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_S, Event.CTRL_MASK));
	   
	   // Create the save as menu item and add an action listener.	   
	   JMenuItem saveAsItem = new JMenuItem(saveAsMenuText);
	   saveAsItem.addActionListener(this);

	   // Create the exit menu item and add an action listener and accelerator.
	   JMenuItem exitItem = new JMenuItem(exitMenuText);
	   exitItem.addActionListener(new ExitListener());
	   exitItem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_X, Event.CTRL_MASK));

	   // Add the sub-menus to the File menu.
	   add(newItem);
	   add(openItem);
	   add(saveItem);
	   add(saveAsItem);
	   add(exitItem);
	}
	
	
	//*************************************************************************
	// Action Listeners
	//*************************************************************************
	
	// Handles the event generated when the user selects 
	// the exit option from the File menu.
	private class ExitListener implements ActionListener {
		public void actionPerformed(ActionEvent e) {
			System.exit(0);
		}
	}
	
	/**************************************************************************
	 * Handles the events generated by the user selecting
	 * a file submenu option.
	 * @param se the selected event and source 
	 *************************************************************************/
	 public void actionPerformed(ActionEvent se) {
		 String selectedCommand = se.getActionCommand();
	 	 	 
		 if (selectedCommand == newMenuText) {
			 UMLWindow.getUMLPanel().changeModel(new UMLModel());
		 }
		 else if (selectedCommand == openMenuText) {
			 UMLWindow.getUMLPanel().load();
		 }
		 else if (selectedCommand == saveMenuText) {
			 UMLWindow.getUMLPanel().save(UMLWindow.getUMLPanel().model().serialize());
		 }
		 else if (selectedCommand == saveAsMenuText) {
			 UMLWindow.getUMLPanel().saveAs(UMLWindow.getUMLPanel().model().serialize());
		 }
	 }
}
