package edu.millersville.cs.segfault.ui.menu;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

import javax.swing.JCheckBox;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JMenu;

import edu.millersville.cs.segfault.ui.UMLWindow;
import edu.millersville.cs.segfault.ui.console.Console;

/**************************************************************************
 * A menu for enabling and disabling subviews and the toolbar in the main 
 * window.
 * @author Daniel Rabiega, Kimberlyn Broskie, 
 *************************************************************************/
public class ViewMenu extends JMenu implements ActionListener {
	
	//*************************************************************************
	// Static Instance Variables
	//*************************************************************************
	private static final long serialVersionUID = 4310696522154979212L;
	private static final String hideToolbarText = "Show Toolbar";

	//*************************************************************************
	// Instance Variables
	//*************************************************************************
	private boolean consoleOn = false;
	private UMLWindow parent;
	
	private JCheckBoxMenuItem consoleItem;
	private JCheckBox toolbarCheckBox;

	private Console console=null;
	
	
	/**************************************************************************
	 * Builds a viewMenu and initializes it with a reference to it's parent.
	 * @param parent the frame for the interface
	 *************************************************************************/
	public ViewMenu(UMLWindow parent) {
		super("View");
		this.parent = parent;
		
		// Create a checkbox to show/hide the toolbar.
		toolbarCheckBox = new JCheckBox(hideToolbarText);
		toolbarCheckBox.setSelected(true);
		toolbarCheckBox.addItemListener(new CheckBoxListener());
		this.add(toolbarCheckBox);
		
		// Create a checkbox to show/hide the console.
		this.consoleItem = new JCheckBoxMenuItem("Console");
		consoleItem.addActionListener(this);
		consoleItem.setActionCommand("CONSOLE");
		this.add(consoleItem);
	}
	
	
	/**************************************************************************
	 * Toggles the console view on and off.
	 * @param e the selected event and source 
	 *************************************************************************/
	@Override
	public void actionPerformed(ActionEvent e) {
		if (e.getActionCommand().equals("CONSOLE")) {
			if (consoleOn) {
				parent.remove(consoleItem);
			} else {
				if (console == null) {
					this.console = new Console();
				}
				parent.add(console, BorderLayout.SOUTH);
				parent.pack();
			}
			consoleOn = !consoleOn;
		}
	}
	
	 
	/**************************************************************************
	 * Private inner class that handles the events generated by the user 
	 * clicking a CheckBox.
	 * @param e the selected event and source 
	 *************************************************************************/
	 private class CheckBoxListener implements ItemListener {
		 public void itemStateChanged(ItemEvent e)
	     {
			 if (toolbarCheckBox.isSelected()) {
				 parent.getToolbar().setVisible(true);
			 }
			 else {
				 parent.getToolbar().setVisible(false);
	         }
	     }
	 }
}
